### PR TITLE
Show progress every once in a while

### PR DESCRIPTION
**Pull request by Sam1370**
This pull request shows the progress of the installation every once in a while. This isn't perfect by any means, although I think it could be mildly useful. 

Ideally, this would be a progress bar that is persistent and stays at the bottom of the screen, and updates when a function is called, although I do not know how to implement that.

### CODE REVIEW

**Comment by Sam1370** [comment]
Here is a demonstration:
https://www.youtube.com/watch?v=OZSUEVTSmpM

**Comment by vilhelmprytz** [comment]
Thank you for your contribution! I really like the idea of displaying some form of progress bar once a while. Is it possible to create a progress bar without using a third-party script? Or perhaps make a copy of the source script into this project? (license and copyright notices from the original author kept, of course!)

Also, because of the many changes in #52 for the pterodactyl 1.0 version of the script, are you able to write these changes using `pterodactyl-1.0` as your base branch (e.g. start from 1.0 modified version of the script)? In that way, your work doesn't have to be rewritten for 1.0 :slightly_smiling_face:

**Comment by vilhelmprytz** [comment]
Perhaps we can find a middle-point here, copying something from StackOverflow isn't exactly great when it comes to copyright and such, is it possible to use `tput` and write something similar?

**Comment by Linux1231233** [comment]
At least I can write anything like this. It is too hard for me :)

**Comment by vilhelmprytz** [comment]
Since this has failing builds, merge conflicts, and there is another PR solving the same issue (#87), I am closing this.

**Pull request closed without merging**
