### PR TITLE
panel: Update PHP version to 8.1

### PR DESCRIPTION
**Pull request by drylian**
php 8.1 version update

Fixes #php new version support for debian and ubuntu (php8.1) pterodactyl not have sup for old versions

### CODE REVIEW

**Comment by Linux123123** [comment]
PHP version is already updated in #344.

**Comment by drylian** [comment]
> PHP version is already updated in #344.
> 
> _Also this wouldn't install php8.1. You have only changed the socket_

Sorry I forgot to change this dependency, now the file is correct, pterodactyl in the latest version no longer supports php 8.0 and 7.4 deprecated

https://pterodactyl.io/panel/1.0/updating.html

**Comment by Linux123123** [comment]
On CentOS 7 & 8, PHP is still on version 8.0. Please also change it to 8.1.

**Comment by drylian** [comment]
> On CentOS 7 & 8, PHP is still on version 8.0. Please also change it to 8.1.

Done?

**Review by Linux123123 — APPROVED** [review]
LGTM

**Pull request merged**
