### PR TITLE
Cleaning up the code a bit

### PR DESCRIPTION
**Pull request by MrFlacko**
Changes literally nothing, just some nicer code for determining if the OS is supported.

### CODE REVIEW

**Comment by Linux123123** [comment]
This is already done in my panel PR #100  and also the way you did it still looks really cluttered.

**Comment by MrFlacko** [comment]
idk I think mine still looks nicer.
Very clear what it does and easy to follow. If something needs to be changed or added it's extremely straight forward.

I think how the case statements work is very cluttered

Doesn't really matter though, doesn't make any changes. If it isn't approved then I just won't bother with this style anymore.


This
```
check_os_comp() {
  SUPPORTED=false
  case "$OS" in
    ubuntu)
      PHP_SOCKET="/run/php/php7.4-fpm.sock"
      [ "$OS_VER_MAJOR" == "18" ] && SUPPORTED=true
      [ "$OS_VER_MAJOR" == "20" ] && SUPPORTED=true
      ;;
    debian)
      PHP_SOCKET="/run/php/php7.4-fpm.sock"
      [ "$OS_VER_MAJOR" == "9" ] && SUPPORTED=true
      [ "$OS_VER_MAJOR" == "10" ] && SUPPORTED=true
      ;;
    centos)
      PHP_SOCKET="/var/run/php-fpm/pterodactyl.sock"
      [ "$OS_VER_MAJOR" == "7" ] && SUPPORTED=true
      [ "$OS_VER_MAJOR" == "8" ] && SUPPORTED=true
      ;;
    *)
      SUPPORTED=false ;;
  esac

  # exit if not supported
  if [ "$SUPPORTED" == true ]; then
    echo "* $OS $OS_VER is supported."
  else
    echo "* $OS $OS_VER is not supported"
    print_error "Unsupported OS"
    exit 1
  fi
}
```

and This
```
function check_os_comp {
    SUPPORTED=false
    [[ "$OS" == "ubuntu" && "$OS_VER_MAJOR" == "18" ]] && PHP_SOCKET="/run/php/php7.4-fpm.sock" && SUPPORTED=true
    [[ "$OS" == "ubuntu" && "$OS_VER_MAJOR" == "20" ]] && PHP_SOCKET="/run/php/php7.4-fpm.sock" && SUPPORTED=true
    [[ "$OS" == "debian" && "$OS_VER_MAJOR" == "9" ]] && PHP_SOCKET="/run/php/php7.4-fpm.sock" && SUPPORTED=true
    [[ "$OS" == "debian" && "$OS_VER_MAJOR" == "10" ]] && PHP_SOCKET="/run/php/php7.4-fpm.sock" && SUPPORTED=true
    [[ "$OS" == "centos" && "$OS_VER_MAJOR" == "7" ]] && PHP_SOCKET="/var/run/php-fpm/pterodactyl.sock" && SUPPORTED=true
    [[ "$OS" == "centos" && "$OS_VER_MAJOR" == "8" ]] && PHP_SOCKET="/var/run/php-fpm/pterodactyl.sock" && SUPPORTED=true

    # exit if not supported
    [[ "$SUPPORTED" == true ]] && echo "* $OS $OS_VER is supported."
    [[ "$SUPPORTED" == false ]] && echo "* $OS $OS_VER is not supported" && print_error "Unsupported OS" && exit 1
}
```

**Comment by MrFlacko** [comment]
I just really dislike if statements in bash

if
elif
else
fi

that sort of stuff, not needed

**Comment by Linux123123** [comment]
Then my is more efficient because I am using case and not checking for every OS and version every time. Also your code is very long in right and uses a lot of `&&`. Also not everything comes up to liking, but about functionality and readability.

**Comment by MrFlacko** [comment]
yours might be more functional but i think mine is more readable and looks a bit nicer

probably useless attributes in this small of a scenario

**Comment by vilhelmprytz** [comment]
Thanks for your contribution. I don't really care about the styling although I  like the use of `case` since the lines aren't too long. If it weren't for #100 I would definitely accept this as well. Closing due to duplicate.

**Pull request closed without merging**
