### PR TITLE
Fixing nginx stopping the script

### PR DESCRIPTION
**Pull request by Linux1231233**
When you choose ASSUME_SSL true, and LETSENCRYPT false the nginx will fail at the end of the script. This fixes that.

### CODE REVIEW

**Comment by vilhelmprytz** [comment]
Thank you for the contribution! I'll look into it and review it ASAP!

**Comment by Linux1231233** [comment]
I saw you prefer one liners  so there it is:
`{ [ "$CONFIGURE_LETSENCRYPT" == true ] || { [ "$CONFIGURE_LETSENCRYPT" == false ] && [ "$ASSUME_SSL" == false ]; }; } && systemctl restart nginx`

**Comment by vilhelmprytz** [comment]
> I saw you prefer one liners  so there it is:
> `{ [ "$CONFIGURE_LETSENCRYPT" == true ] || { [ "$CONFIGURE_LETSENCRYPT" == false ] && [ "$ASSUME_SSL" == false ]; }; } && systemctl restart nginx`

Wow, that's very much shorter. I reckon it's actually more readable with the one you initially wrote. What do you think?

**Comment by Linux1231233** [comment]
That is exactly why I didn't push it to the PR and just commented.

**Pull request merged**
